### ISSUE TITLE
Why do methods that require authentication (like getFriends) not work?

### ISSUE THREAD

**Issue by simonv3** [bdickason/node-goodreads#11]
Everything looks right?

I realize that if you knew they would probably work, but thought I'd ask in case it's an easy fix, or whether you had any more insight?

**Comment by hueyy** [comment]
`oa.get @options.path, accessToken, accessTokenSecret...` seems to work where `oa.getProtectedResource @options.path, 'GET', accessToken, accessTokenSecret...` doesn't. 

In `processCallback`, there's already an `oauth` request to `http://www.goodreads.com/api/auth_user` to get the username and userid of the authenticated user, so I don't see why getFriends shouldn't work.

**Comment by rharriso** [comment]
@hueyy added a `protectedRequest` method, that could be useable for other requests.
