### ISSUE TITLE
Would love promises (or node-style callback functions)

### ISSUE THREAD

**Issue by abacon** [bdickason/node-goodreads#17]
I'd love to be able to promisify this library using something like https://github.com/thenables/thenify or https://github.com/sindresorhus/pify. Unfortunately, these (and all other promisify libraries I could find...) expect callback functions to be in the node callback style, namely `callback(err, result)`. Because `node-goodreads` uses callbacks of the style `callback(result)`, promisification libraries think that every response has an error!

The other possibility, of course, is that the library is modified to allow either promises or callbacks. There are probably some utilities out there to make this easy, but I'm not aware of any off the top of my head.

What do you think? Thanks so much!

**Comment by hueyy** [comment]
I'd be willing to convert all the methods to [ES6 promises](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise) i.e.

    sampleMethod: (input, callback) ->
      #do stuff
      callback(result)

will become

    sampleMethod: (input) ->
      return new Promise ((resolve, reject) ->
        #do stuff
        if error
          reject(error)
        else
          resolve(result)

This won't be backwards compatible though, and you'll have to use `.then` and `.catch` to access the function results and errors respectively.

The current node LTS version (v6.1.0) [already supports](http://node.green) ES6 promises.

**Comment by rharriso** [comment]
Thats fine with me.

**Comment by hueyy** [comment]
Think we can close this issue now.

**Comment by rharriso** [comment]
:+1:
