### ISSUE TITLE
Ethics of forking?

### ISSUE THREAD

**Issue by kylegoetz** [bdickason/node-goodreads#39]
Hey, I forked this and added a couple new methods and made everything async/await instead of old Node-style callbacks.

I'm updating the readme and going to publish on NPM but wasn't sure the ethics of just leaving your excellent readme intact but with a couple updates, plus changing "author" in package.json to "contributors" because author is a single string while contributors is an array (so can credit you plus add myself).

Anyway, let me know your thoughts I guess in the next few days.

**Comment by rharriso** [comment]
I'm fine with this. I haven't actively contributed in a couple of years. I know @bdickason is inactive back then.

**Comment by kylegoetz** [comment]
Cool, thanks.
