### ISSUE TITLE
Pagination getSingleShelf

### ISSUE THREAD

**Issue by chrifmarwen** [bdickason/node-goodreads#5]
Goodreads api is offering a pagination option that the library dosn't seem to handle.

**Comment by sillygwailo** [comment]
I implemented this for an app I was working on, and just made a pull request. See #6. This pull request changes the API, so the example is updated to reflect that.

**Comment by bdickason** [comment]
Thanks @sillygwailo! Could you also update the README so users know that this is an optional input for getSingleShelf? :)

**Comment by sillygwailo** [comment]
This is implemented in the current repository, though the version number needs to be bumped and published to npmjs.com. @bdickason, can you do this? That way I can stop relying on my fork for my own project.

**Comment by bdickason** [comment]
I merged this a while ago but didn't close this task. #6 fixes this issue.
