### ISSUE TITLE
Recommendations

### ISSUE THREAD

**Issue by caiovaccaro** [bdickason/node-goodreads#7]
Is there any way to get recommendations?

**Comment by bdickason** [comment]
The only API endpoint I see that mentions recommendations is `/recommendations/ID` shown below:

````
URL: https://www.goodreads.com/recommendations/ID?format=xml 
HTTP method: GET 
Parameters: 
id: recomendation id
````

This looks like a friend to friend recommendation but not their automated recommendation engine. I do not see a way to access that data currently.

Here is the full goodreads API documentation if you want to take a look: https://www.goodreads.com/api/index#recommendations.show

**Comment by caiovaccaro** [comment]
Yeah I saw that. But I could not find a way to get a recommendation ID
either.

Thanks!

Em domingo, 14 de junho de 2015, Brad Dickason <notifications@github.com>
escreveu:
