### ISSUE TITLE
Oauth callback : result.user['@'] is undefined 

### ISSUE THREAD

**Issue by tomahim** [bdickason/node-goodreads#9]
I tried to run the booklist.js example, and I get an error when using oauth authentification. 

I get result.user['@'] is undefined on line 97 in goodreads.js file. 

I suppose the returned data has changed.

**Comment by jesusmacedo** [comment]
I had the same issue. 

Just change the @ for $ and this will solve the issue. Make this change to the line 100 as well.

Greetings.

**Comment by tomahim** [comment]
Yes, something like this made the trick on line 97 : result.GoodreadsResponse.user[0]['$'].id

Thank you

**Comment by bdickason** [comment]
Thanks for reporting this! I just revved the npm package as well so now npm install should work as expected. :+1:

**Comment by bdickason** [comment]
Also added 9ee28e6 to finally fix this.
